import json
import os
from datetime import datetime


def calculate_compliance_score(results):
    scored  = [r for r in results if r["severity"] not in ("INFO",)]
    passing = [r for r in scored  if r["status"] == "PASS"]
    failing = [r for r in scored  if r["status"] == "FINDINGS"]
    errors  = [r for r in scored  if r["status"] == "ERROR"]

    score = round((len(passing) / len(scored)) * 100, 1) if scored else 0

    critical_findings = [
        r for r in results
        if r["severity"] == "CRITICAL" and r["status"] == "FINDINGS"
    ]

    return {
        "overall_score":     score,
        "total_controls":    len(results),
        "scored_controls":   len(scored),
        "passing_controls":  len(passing),
        "failing_controls":  len(failing),
        "error_controls":    len(errors),
        "critical_findings": len(critical_findings)
    }


def generate_json_report(results, score, report_dir):
    today     = datetime.now().strftime("%Y-%m-%d")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = {
        "report_metadata": {
            "generated_at":   timestamp,
            "report_date":    today,
            "system":         "PaySecure Security Control Validator",
            "report_version": "1.0"
        },
        "compliance_score": score,
        "controls": results
    }

    filename = f"compliance-report-{today}.json"
    filepath = os.path.join(report_dir, filename)

    with open(filepath, "w") as f:
        json.dump(report, f, indent=2, default=str)

    return filepath


def generate_markdown_report(results, score, report_dir):
    today     = datetime.now().strftime("%Y-%m-%d")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = []
    lines.append("# Security Control Assessment Report")
    lines.append("")
    lines.append("## Report Details")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append(f"| Generated | {timestamp} |")
    lines.append(f"| System | PaySecure Security Control Validator |")
    lines.append(f"| Assessment Date | {today} |")
    lines.append("")

    score_val = score["overall_score"]
    if score_val >= 80:
        icon = "✅"
        label = "GOOD STANDING"
    elif score_val >= 60:
        icon = "⚠️"
        label = "NEEDS ATTENTION"
    else:
        icon = "🚨"
        label = "CRITICAL ISSUES"

    lines.append("## Compliance Score")
    lines.append("")
    lines.append(f"### {icon} Overall Score: {score_val}% — {label}")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total Controls | {score['total_controls']} |")
    lines.append(f"| Passing | {score['passing_controls']} |")
    lines.append(f"| With Findings | {score['failing_controls']} |")
    lines.append(f"| Critical Findings | {score['critical_findings']} |")
    lines.append("")

    critical = [
        r for r in results
        if r["severity"] == "CRITICAL" and r["status"] == "FINDINGS"
    ]
    if critical:
        lines.append("## Critical Findings")
        lines.append("")
        for r in critical:
            lines.append(f"### {r['control_id']}: {r['name']}")
            lines.append(f"- **Findings:** {r['finding_count']}")
            lines.append(f"- **Framework:** {r['framework']}")
            lines.append("")

    lines.append("## All Controls")
    lines.append("")
    lines.append("| ID | Name | Severity | Status | Findings |")
    lines.append("|----|------|----------|--------|----------|")

    for r in results:
        if r["status"] == "PASS":
            s = "PASS"
        elif r["status"] == "FINDINGS":
            s = "FINDINGS"
        else:
            s = "ERROR"

        lines.append(
            f"| {r['control_id']} | {r['name']} | "
            f"{r['severity']} | {s} | {r['finding_count']} |"
        )

    lines.append("")
    lines.append("---")
    lines.append("*Generated by PaySecure Security Control Validator*")

    filename = f"compliance-report-{today}.md"
    filepath = os.path.join(report_dir, filename)

    with open(filepath, "w") as f:
        f.write("\n".join(lines))

    return filepath
