"""
generate_report.py
==================
Generates cloud security reports from validation findings.
"""

import json
import os
from datetime import datetime


def generate_report(iam_findings, s3_findings, report_dir):
    """
    Combine all findings and generate JSON and Markdown reports.

    Args:
        iam_findings: list of IAM finding dicts
        s3_findings:  list of S3 finding dicts
        report_dir:   path to reports folder

    Returns:
        tuple: (json_path, markdown_path)
    """
    today     = datetime.now().strftime("%Y-%m-%d")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    all_findings = iam_findings + s3_findings

    critical = [f for f in all_findings if f["severity"] == "CRITICAL"]
    high     = [f for f in all_findings if f["severity"] == "HIGH"]
    medium   = [f for f in all_findings if f["severity"] == "MEDIUM"]
    low      = [f for f in all_findings if f["severity"] == "LOW"]

    report = {
        "metadata": {
            "generated_at":  timestamp,
            "report_date":   today,
            "system":        "PaySecure AWS Cloud Validator"
        },
        "summary": {
            "total_findings":    len(all_findings),
            "critical_count":    len(critical),
            "high_count":        len(high),
            "medium_count":      len(medium),
            "low_count":         len(low),
            "iam_findings":      len(iam_findings),
            "s3_findings":       len(s3_findings)
        },
        "findings": all_findings
    }

    json_path = os.path.join(report_dir, f"cloud-report-{today}.json")
    with open(json_path, "w") as f:
        json.dump(report, f, indent=2)

    lines = []
    lines.append("# AWS Cloud Security Assessment Report")
    lines.append("")
    lines.append(f"**Generated:** {timestamp}")
    lines.append(f"**System:** PaySecure AWS Cloud Validator")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    lines.append(f"| 🚨 Critical | {len(critical)} |")
    lines.append(f"| 🔴 High | {len(high)} |")
    lines.append(f"| 🟡 Medium | {len(medium)} |")
    lines.append(f"| 🟢 Low | {len(low)} |")
    lines.append(f"| **Total** | **{len(all_findings)}** |")
    lines.append("")

    if critical:
        lines.append("## Critical Findings — Immediate Action Required")
        lines.append("")
        for f in critical:
            lines.append(f"### {f['control_id']}: {f['title']}")
            lines.append(f"- **Resource:** `{f['resource']}`")
            lines.append(f"- **Description:** {f['description']}")
            lines.append(f"- **Framework:** {f['framework']}")
            lines.append(f"- **Remediation:** {f['remediation']}")
            lines.append("")

    if high:
        lines.append("## High Severity Findings")
        lines.append("")
        for f in high:
            lines.append(f"### {f['control_id']}: {f['title']}")
            lines.append(f"- **Resource:** `{f['resource']}`")
            lines.append(f"- **Description:** {f['description']}")
            lines.append(f"- **Remediation:** {f['remediation']}")
            lines.append("")

    if medium or low:
        lines.append("## Medium and Low Severity Findings")
        lines.append("")
        lines.append("| Control ID | Title | Severity | Resource |")
        lines.append("|------------|-------|----------|----------|")
        for f in medium + low:
            lines.append(
                f"| {f['control_id']} | {f['title']} "
                f"| {f['severity']} | `{f['resource']}` |"
            )
        lines.append("")

    lines.append("## Remediation Priority")
    lines.append("")
    lines.append("| Priority | Finding | Action |")
    lines.append("|----------|---------|--------|")
    for i, f in enumerate(critical + high, 1):
        lines.append(
            f"| {i} | {f['title']} ({f['resource']}) "
            f"| {f['remediation'][:60]}... |"
        )
    lines.append("")
    lines.append("---")
    lines.append("*Generated by PaySecure AWS Cloud Validator*")

    md_path = os.path.join(report_dir, f"cloud-report-{today}.md")
    with open(md_path, "w") as f:
        f.write("\n".join(lines))

    return json_path, md_path
